seed_games = [
  { name: "Popcorn", num_of_players: {"min"=>"3", "max"=>"30"}, equipment: "ball (soft)", noise: true, time_range: {"min"=>"5", "max"=>"30"}, description: "Players stand in a cricle. One person throws the ball in the air, claps once, and catches the ball without dropping it. All of the others players do the same as the ball makes its way around the circle. When the ball reaches the person who went first, they throw it in the air, clap twice and catch it. With each round, the number of claps increases. Players who don’t clap the proper number of times, or drop the ball are out. Last person standing is the winner." },

  { name: "Protect the President", num_of_players: {"min"=>"7", "max"=>"20"}, equipment: "ball (soft)", noise: true, time_range: {"min"=>"5", "max"=>"30"}, description: "Players stand in a large circle with two people in the middle. One person is the president, and the other is secret service. Players try to hit the president with the ball while secret service protects the president. Secret service and president are free to move within the circle. Other players cannot move around. If the ball touches the president at any time, the person who threw the ball becomes secret service. Secret service becomes the president and the former president joins the circle." },

  { name: "Wink", num_of_players: {"min"=>"8", "max"=>"20"}, equipment: nil, noise: false, time_range: {"min"=>"10", "max"=>"30"}, description: "Players are sitting in a circle so they can see everyone. To start, everyone puts their heads down. The adult taps one player on the head. This person in the winker. Everyone opens their eyes. The winker eliminates other players by winking at them. If you are winked at, silently count to 5, then announce that you're out and put your head down. If the winker eliminates everyone, then they win. If a player thinks they know who the winker is, before they get winked at, they can raise their hand and say they have a suspect. Such as 'I suspect that Sally is the winker.' If Sally is not the winker, then the accuser is eliminated." },

  { name: "Musical Chairs", num_of_players: {"min"=>"5", "max"=>"30"}, equipment: "boombox", noise: true, time_range: {"min"=>"10", "max"=>"30"}, description: "You know drill. Don't forget to start with one less chair than there are players." },

  { name: "Dollar Bill Grab", num_of_players: {"min"=>"1", "max"=>"30"}, equipment: nil, noise: false, time_range: {"min"=>"5", "max"=>"15"}, description: "Players stand with their backs and heels against the wall. Put a dollar bill (or coin) underneath the toe of one shoe on the ground. The player tries to bend down and pick up the dollar bill without losing balance while having your heels staying in the same place (like a toe touch against the wall)." },

  { name: "Radar", num_of_players: {"min"=>"6", "max"=>"15"}, equipment: "ball", noise: false, time_range: {"min"=>"5", "max"=>"30"}, description: "Place a chair in the middle of a circle of sitting players. Underneath the chair place a ball, set of keys, eraser or any object. Choose one player who will sit in the chair with a blindfold on or their eyes closed. The object of the game is for a player to steal the object placed underneath the chair, without the blindfolded member hearing them. Only one player can attempt a heist at a time, as determined by you. The person in the middle has two guesses where the can point if they hear someone. If they point directly at the player attempting the heist, the player in the chair joins the circle and someone else is chosen to sit in the chair." },

  { name: "Zookeeper", num_of_players: {"min"=>"15", "max"=>"40"}, equipment: nil, noise: true, time_range: {"min"=>"10", "max"=>"30"}, description: "You need an area large enough for your group to run around in. Select 1-3 players to be the Zookeepers and have the rest of the group line up on either side of the field. Each player must select an animal and keep it a secret from everyone else. Zookeepers will then call out commands such as “Escape the Zoo if your animal has feathers!” or “Escape the Zoo if your animal swims!” If the command applies to a player, they try to run to the other side of the field without the Zookeepers tagging them. If a member is tagged they become a stone and must sit down where they were tagged." },

  { name: "Uncle Sam", num_of_players: {"min"=>"15", "max"=>"40"}, equipment: nil, noise: true, time_range: {"min"=>"10", "max"=>"30"}, description: "You need an area large enough for your group to run around in. Select 1-3 players to be Uncle Sam and the rest of the group line up on either side of the field. All players chant, \"Uncle Sam, Uncle Sam, may we cross your river?!\" Uncle Sam says, \"only if you're wearing green\" or \"only if you're in the 5th grade,\" etc. If the condition applies to you, you run across the river and try not to get tagged by Uncle Sam. If you are tagged, you are now a rock in the river. You sit down and can tag people if they come near you." },

  { name: "Triangle Tag", num_of_players: {"min"=>"4", "max"=>"20"}, equipment: nil, noise: true, time_range: {"min"=>"5", "max"=>"30"}, description: "You need an area large enough for your group to move around in. Groups of four. Every group is playing their own game. Three players hold hands and the fourth player is \"it.\" Whoever is \"it\" chooses one of the three players to tag. When the game starts, the player who is \"it\" tries to tag the player they chose while the two players holding hands with that player try to prevent them from getting tagged. Reaching across the triangle, either over or under the hands, is not allowed. When the player is tagged, switch roles. " },

  { name: "Rock, Paper, Scissors Tag", num_of_players: {"min"=>"10", "max"=>"40"}, equipment: nil, noise: true, time_range: {"min"=>"10", "max"=>"30"}, description: "You need a moderately large area for your group to run around in. Two teams. Each team huddles up and quietly decides to throw \"rock,\" \"paper,\" or \"scissors.\" Then, players stand in the middle shoulder to shoulder with their team and face to face with the opposing team. On \"Go!\" everyone plays one game of rock, paper, scissors with the person in front of them, using the pre-determined rock, paper, or scissors. If your team looses that round, you turn and run to the wall of the gym, or past a pre-determined line. If you make it without getting tagged by the other team, you are safe. If you were tagged, you are now a part of the other team. If your team wins the round of rock, paper, scissors, you try to tag people from the other team. The game ends when everyone ends up on one team."},

  { name: "People to People", num_of_players: {"min"=>"2", "max"=>"50"}, equipment: nil, noise: false, time_range: {"min"=>"5", "max"=>"15"}, description: "Players find a partner and stand next to them. Whatever combination of body parts you call out, the partners have to make those connections. For example, \"back to back,\" \"toe to toe,\" \"knee to elbow.\" When you call \"People to People,\" players find a new partner. You can play so each command adds on the previous so it starts looking like twister. Or not."},

  { name: "Group Juggle", num_of_players: {"min"=>"2", "max"=>"10"}, equipment: "ball (soft)", noise: true, time_range: {"min"=>"5", "max"=>"20"}, description: "Throw the ball in the air. Players try to prevent the ball from hitting the ground by hitting it the air. Catching or holding on to the ball is not allowed."},

  { name: "Helium Hoops", num_of_players: {"min"=>"5", "max"=>"30"}, equipment: "hula-hoops", noise: false, time_range: {"min"=>"10", "max"=>"20"}, description: "FRUSTRATION WARNING. Five to 10 players stand in a circle with their index fingers outstretched. Rest a hula-hoop on each group's fingers, instructing them not to grab it. The goal is to lower the hoop to the ground with everyone remaining in contact with the hoop at all times. (Can also be played with a long stick.)"},

  { name: "Screaming Toes", num_of_players: {"min"=>"10", "max"=>"20"}, equipment: nil, noise: true, time_range: {"min"=>"5", "max"=>"15"}, description: "Players stand in a close circle. When you say, \"Look down,\" each person looks down at someone else's feet. When you say, \"Look up,\" each person quickly looks up at the face of another person. If two people are looking at each other, they scream! They sit down and are no longer in the game. Or not."},

  { name: "Would You Rather? (Either, Or)", num_of_players: {"min"=>"2", "max"=>"40"}, equipment: nil, noise: false, time_range: {"min"=>"5", "max"=>"15"}, description: "Would You Rather usually makes players pick between two bad or weird things. Either, Or has them choose between two good things. You ask a question, like, \"Would you rather jump in a pool of jello, or in a pool of spaghetti.\" Or \"tacos or burritos,\" \"ice cream or cake,\" \"soccer or basketball.\" There are many ways to play this. In a big room, players can start in the middle and run to either side."},

  { name: "Four Corners", num_of_players: {"min"=>"10", "max"=>"40"}, equipment: nil, noise: false, time_range: {"min"=>"10", "max"=>"20"}, description: "Assign each corner of the room (or objects outside) the numbers 1 - 4. One player stands in the middle with their eyes closed and counts to 10. All other players scurry to whatever corner they want. When the person in the middle is done counting, they call out a number 1 - 4. All players in that corner are out. The game continues until there is one, or no players left."},

  { name: "Ships and Sailors", num_of_players: {"min"=>"15", "max"=>"50"}, equipment: nil, noise: true, time_range: {"min"=>"15", "max"=>"30"}, description: "You need an area large enough for your group to move around in. Everyone starts out standing facing you. You will call out commands and if a player messes up or is the \"odd man out,\" they are out of the game. Some commands might include: \nStarboard: Everyone runs to their right.\nPort: Everyone runs to their left.\nHit the Deck: All players quickly lie on their stomach.\nCaptain's Coming!: All players stand at \"attention\" (in a salute), and can’t move from this position until you say, \"At Ease, Sailors!\"\nMan Overboard: Sailors must find a partner. One person drops to one knee the other stands behind them, puts a hand on their shoulder. Both scan the ocean for the overboard man.\nThree Sailors Eating: Players form groups of three, sit down in a circle and start pretending to eat.\nFour Sailors Rowing: Players form groups of four and sit in a row and pretend like they're rowing a boat.\nWalk the Plank: Five people stand in a single file row, hands on the shoulders of the person in front of them and walk forward.\n(Other ideas: Seasick: Everyone finds a partner. One person bends over and the other person pretends to throw up over them. Mermaid: Stand on one foot, one hand on hip and wave while saying, in a mermaid voice, \"Hi, sailors.\")"},

  { name: "Hula-Hoop Pass", num_of_players: {"min"=>"10", "max"=>"50"}, equipment: "hula-hoops", noise: true, time_range: {"min"=>"10", "max"=>"20"}, description: "Players form circles of about 10 and hold hands. You need at least one hula-hoop per circle. Place the hula-hoop in between two players so it's resting on top of their hands. Players pass the hula-hoop around the circle while holding hands. You can time them to see how fast they can get it around the circle, or opposing teams can try to beat each other. You can also play with two hula-hoops in one circle." },

  { name: "Dead Ant Tag", num_of_players: {"min"=>"10", "max"=>"40"}, equipment: nil, noise: true, time_range: {"min"=>"10", "max"=>"30"}, description: "When a player gets tagged, they lie on their back with their arms and legs sticking straight up in the air. The tagged player can get rescued and back in the game if four other players each grab a limb. (You can play so that the \"dead ant\" needs to be carried to a designated spot before they are revived.)" },

  { name: "Groups Of...", num_of_players: {"min"=>"20", "max"=>"50"}, equipment: "boombox", noise: true, time_range: {"min"=>"10", "max"=>"25"}, description: "Similar to musical chairs. Players mingle while the music is playing. When you stop the music, call out a number and players have to form groups of that size. Whoever is the \"odd man out\" is out of the game. Or you could play that the \"odd man out\" has to do something silly in front of the group. " }
]

seed_games.each do |seed|
  new_game = Game.create(seed)
  new_game.save
end
